### PR TITLE
Changed mysql base url to point to cdn

### PR DESCRIPTION
**Pull request by retpolanne**
The MYSQL_BASE_URL was pointing to an URL which returned a 302 response and this buildpack was failing.

### CODE REVIEW

**Comment by fernap3** [comment]
I just ran into the same error.  Would be great to get this merged.  For now I'm going to fork and apply the change for myself.

**Comment by retpolanne** [comment]
If you want to, you can use my fork.

**Comment by fernap3** [comment]
Thanks!  I think I’ll end up actually hosting a MySQL binary myself on S3 so I can be sure it’s always available at the same place.  Then fetch it from there with a custom fork of this build pack.

**Comment by retpolanne** [comment]
Good idea!

**Pull request closed without merging**
